apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  project: default
  server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/urbeingwatched8/loberta_test_task.git'
    targetRevision: HEAD
    path: app
  destination:
    server: http://localhost
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      
